### ISSUE TITLE
CentOS8 errors while installing feedsim/tao bench

### ISSUE THREAD

**Issue by CoolBlueSam** [facebookresearch/DCPerf#57]
Seeing errors while installing feedsim/tao bench (I believe within one of the folly packages)

FAILED: rsocket-prefix/src/rsocket-stamp/rsocket-build staging/usr/local/lib/libReactiveSocket.a staging/usr/local/lib/libyarpl.a
cd /DCPerf/benchmarks/feedsim/src/build/third_party/rsocket-cpp && /DCPerf/benchmarks/feedsim/third_party/cmake-3.14.5/staging/bin/cmake --build . && /DCPerf/benchmarks/feedsim/third_party/cmake-3.14.5/staging/bin/cmake -E touch /DCPerf/benchmarks/feedsim/src/build/rsocket-prefix/src/rsocket-stamp/rsocket-build

/DCPerf/benchmarks/feedsim/src/third_party/rsocket-cpp/yarpl/Refcounted.h:45:23: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
[47/58] Building CXX object CMakeFiles/ReactiveSocket.dir/rsocket/internal/ScheduledRSocketResponder.cpp.o
[48/58] Building CXX object CMakeFiles/ReactiveSocket.dir/rsocket/transports/tcp/TcpDuplexConnection.cpp.o
[49/58] Building CXX object CMakeFiles/ReactiveSocket.dir/rsocket/RSocketResponder.cpp.o
FAILED: CMakeFiles/ReactiveSocket.dir/rsocket/RSocketResponder.cpp.o
/opt/rh/gcc-toolset-11/root/usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DGFLAGS_IS_A_DLL=0 -I/DCPerf/benchmarks/feedsim/src/third_party/rsocket-cpp -I/DCPerf/benchmarks/feedsim/src/third_party/rsocket-cpp/yarpl/.. -isystem /usr/include/libdwarf -isystem /DCPerf/benchmarks/feedsim/src/build/staging/usr/local/include -Wall -Wextra -Woverloaded-virtual -g -Wno-noexcept-type -O3 -DNDEBUG -fPIC   -Werror -std=gnu++14 -MD -MT CMakeFiles/ReactiveSocket.dir/rsocket/RSocketResponder.cpp.o -MF CMakeFiles/ReactiveSocket.dir/rsocket/RSocketResponder.cpp.o.d -o CMakeFiles/ReactiveSocket.dir/rsocket/RSocketResponder.cpp.o -c /DCPerf/benchmarks/feedsim/src/third_party/rsocket-cpp/rsocket/RSocketResponder.cpp

Few more errors like these and then:
ninja: build stopped: subcommand failed.

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./benchpress_cli.py", line 16, in <module>
    main()
  File "/DCPerf/benchpress/cli/main.py", line 310, in main
    args.command.run(args, bp.jobs)
  File "/DCPerf/benchpress/cli/commands/install.py", line 75, in run
    install_benchmark(job.install_script, env=env)
  File "/DCPerf/benchpress/lib/util.py", line 89, in install_benchmark
    raise Exception(f"Failed to run '{cmd_str}'")
Exception: Failed to run 'bash -x ./packages/feedsim/install_feedsim.sh'

Am I missing anything?

**Comment by CoolBlueSam** [comment]
ok i think i figured it out..
feedsim doesn't work with gcc-toolset-11 .. whereas taobench needs it.. so both need to be installed separately!!
