### ISSUE TITLE
Mediawiki install reports successful but HHVM failed

### ISSUE THREAD

**Issue by LPettey-Arm** [facebookresearch/DCPerf#63]
Mediawiki is failing the install because HHVM is dumping a seg fault when running Composer during the install process. 

The HHVM seg fault is probably on my side.

The Mediawiki issue is that even after the seg fault, the `benchpress_cli` reports Mediawiki as installed and allows an attempt to run. If HHVM fails during the install step, Benchpress should not report MW as installed and should not allow a run attempt.

````
Composer (version 2.2.24) successfully installed to: /root/DCPerf/oss-performance/composer.phar
Use it: php composer.phar

+ yes
+ /usr/local/hphpi/legacy/bin/hhvm composer.phar install
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.4391.log
./packages/mediawiki/install_oss_performance_mediawiki.sh: line 115:  4390 Broken pipe             yes
      4391 Segmentation fault      (core dumped) | $HHVM composer.phar install
+ echo 1
+ sudo tee /proc/sys/net/ipv4/tcp_tw_reuse
1
+ sudo cp /root/DCPerf/packages/mediawiki/my.cnf /etc/my.cnf
+ '[' centos = ubuntu ']'
+ sudo systemctl restart mariadb
[root@2pgrace-112 DCPerf]# ./benchpress_cli.py run oss_performance_mediawiki_mlp
Will run 1 job(s)
Running "oss_performance_mediawiki_mlp": Tuned +MLP run for oss_performance_mediawiki
Job execution command: ['./packages/mediawiki/run.sh', '-r/usr/local/hphpi/legacy/bin/hhvm', '-nnginx', '-ssiege', '-R0', '-c0', '--', '--mediawiki-mlp', '--siege-duration=10M', '--siege-timeout=11m', '--run-as-root', '--i-am-not-benchmarking']
stdout:
	1
	Core dumped: Segmentation fault
	Stack trace in /tmp/stacktrace.4826.log
stderr:
	./packages/mediawiki/run.sh: line 72:  4826 Segmentation fault      (core dumped) HHVM_DISABLE_NUMA=1 "$_hhvm_path" -vEval.ProfileHWEnable=0 perf.php --nginx "$_nginx_path" --siege "$_siege_path" --hhvm "$_hhvm_path" ${_db_host} --db-username=root --db-password=password --memcached=/usr/local/memcached/bin/memcached --memcached-threads "$MEMCACHE_THREADS" --client-threads "$CLIENT_THREADS" --server-threads "$SERVER_THREADS" --scale-out "${HHVM_SERVERS}" --delay-check-health 30 --hhvm-extra-arguments='-vEval.ProfileHWEnable=0' ${extra_args}
Failed to parse stdout as JSON:
Failed to parse stderr as JSON:
Failed to parse results, this might mean the benchmark failed
stdout:
1
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.4826.log

stderr:
./packages/mediawiki/run.sh: line 72:  4826 Segmentation fault      (core dumped) HHVM_DISABLE_NUMA=1 "$_hhvm_path" -vEval.ProfileHWEnable=0 perf.php --nginx "$_nginx_path" --siege "$_siege_path" --hhvm "$_hhvm_path" ${_db_host} --db-username=root --db-password=password --memcached=/usr/local/memcached/bin/memcached --memcached-threads "$MEMCACHE_THREADS" --client-threads "$CLIENT_THREADS" --server-threads "$SERVER_THREADS" --scale-out "${HHVM_SERVERS}" --delay-check-health 30 --hhvm-extra-arguments='-vEval.ProfileHWEnable=0' ${extra_args}

Traceback (most recent call last):
  File "/root/DCPerf/./benchpress_cli.py", line 16, in <module>
    main()
  File "/root/DCPerf/benchpress/cli/main.py", line 354, in main
    args.command.run(args, bp.jobs)
  File "/root/DCPerf/benchpress/cli/commands/run.py", line 178, in run
    metrics = job.run(args.role, role_in)
  File "/root/DCPerf/benchpress/lib/job.py", line 275, in run
    return self.parser.parse(
  File "/root/DCPerf/benchpress/plugins/parsers/mediawiki.py", line 16, in parse
    metrics = super().parse(stdout, stderr, returncode)
  File "/root/DCPerf/benchpress/plugins/parsers/generic.py", line 50, in parse
    raise ValueError(msg)
ValueError: Couldn't not find or parse JSON from either stdout or stderr`

```

**Comment by excelle08** [comment]
2ad3809 will let installation fail if something in the script fails. We'll push another feature improvement to disallow running un-installed benchmark soon.
